// @artifact dev
// Every file in the repo declares whether it ships to a trainee (`production`)
// or exists only to build, test and document the simulator (`dev`), so a
// release distribution can be stripped mechanically. See docs/dev/ARTIFACT-CLASSES.md.
//
// The marker in each file is the single source of truth. Four files cannot carry
// one -- two are generated and forbidden to hand-edit (UPGRADE-PLAN rule 2), one is
// legal text, one is binary -- so they are classified here and nowhere else.
const test = require('node:test');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');

// path -> [class, why it carries no in-file marker]
const UNMARKABLE = {
  'support.js': ['production', 'generated dc runtime; rule 2 forbids editing it'],
  'dist/experion-station-sim-standalone.html': ['production', 'generated by tools/build-dist.py; rule 2 forbids hand-editing'],
  'LICENSE': ['production', 'legal text, kept verbatim'],
  '.thumbnail': ['dev', 'binary WebP export artifact, not referenced by either build'],
};

function tracked() {
  return execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8' })
    .split('\n').map(s => s.trim()).filter(Boolean);
}

function declaredClass(rel) {
  if (Object.prototype.hasOwnProperty.call(UNMARKABLE, rel)) return UNMARKABLE[rel][0];
  const head = fs.readFileSync(path.join(ROOT, rel), 'utf8').split('\n').slice(0, 3);
  const hits = head.join('\n').match(/@artifact\s+(production|dev)\b/g) || [];
  assert.equal(hits.length > 0, true, `${rel}: no "@artifact production|dev" marker in its first 3 lines`);
  assert.equal(hits.length, 1, `${rel}: ${hits.length} artifact markers, expected exactly 1`);
  return hits[0].split(/\s+/)[1];
}

test('every tracked file declares an artifact class', () => {
  for (const rel of tracked()) declaredClass(rel);
});

test('directories that are wholly dev are classified dev', () => {
  const devDirs = ['tests/', 'tools/', 'docs/dev/'];
  for (const rel of tracked()) {
    if (devDirs.some(d => rel.startsWith(d))) {
      assert.equal(declaredClass(rel), 'dev', `${rel} lives under a dev directory but is not marked dev`);
    }
  }
});

test('the shipping artifacts are classified production', () => {
  const shipped = [
    'Experion Station Simulator.dc.html',
    'Launcher.dc.html',
    'support.js',
    'dist/experion-station-sim-standalone.html',
    'README.md',
    'LICENSE',
    'docs/RESOURCES.md',
  ];
  for (const rel of shipped) {
    assert.equal(declaredClass(rel), 'production', `${rel} must ship`);
  }
  for (const rel of tracked()) {
    if (rel.startsWith('src/')) {
      assert.equal(declaredClass(rel), 'production', `${rel}: src modules are loaded by both builds`);
    }
  }
});

test('CHANGELOG.md is canonical and ships', () => {
  // Anthony, 2026-08-30: "changlog stays canonical". It is the project's record of
  // record, not a build document, and is never stripped from a distribution.
  assert.equal(declaredClass('CHANGELOG.md'), 'production');
});

test('the unmarkable allowlist is exact -- no file on it carries a marker anyway', () => {
  const all = tracked();
  for (const rel of Object.keys(UNMARKABLE)) {
    assert.equal(all.includes(rel), true, `${rel} is on the unmarkable allowlist but is not tracked`);
  }
  for (const [rel, [cls, why]] of Object.entries(UNMARKABLE)) {
    assert.equal(['production', 'dev'].includes(cls), true, `${rel}: bad class ${cls}`);
    assert.equal(typeof why === 'string' && why.length > 10, true, `${rel}: needs a stated reason`);
    if (rel === '.thumbnail') continue; // binary
    const head = fs.readFileSync(path.join(ROOT, rel), 'utf8').split('\n').slice(0, 3).join('\n');
    assert.equal(/@artifact\s+(production|dev)\b/.test(head), false,
      `${rel} is on the unmarkable allowlist but now carries a marker -- take it off the list`);
  }
});

test('stripping every dev file leaves both builds intact', () => {
  // The standalone must not depend on anything dev-class, and the folder build must
  // only need the app page, support.js and src/. This is the property that makes
  // "remove the dev files" a safe release step rather than a hopeful one.
  const dev = tracked().filter(rel => declaredClass(rel) === 'dev');
  const needed = [
    'Experion Station Simulator.dc.html',
    'Launcher.dc.html',
    'support.js',
    'dist/experion-station-sim-standalone.html',
  ];
  for (const rel of needed) {
    assert.equal(dev.includes(rel), false, `${rel} is required by a build and must never be dev-class`);
  }
  const app = fs.readFileSync(path.join(ROOT, 'Experion Station Simulator.dc.html'), 'utf8');
  const localScripts = [...app.matchAll(/<script src="\.\/([^"]+)"/g)].map(m => m[1]);
  assert.equal(localScripts.length > 0, true, 'app loads no local scripts -- regex drifted');
  for (const s of localScripts) {
    assert.equal(dev.includes(s), false, `the app loads ./${s}, which is marked dev`);
  }
});
