// @artifact dev
// Pins the ESS.MODEL_ID contract (V3-PLAN.md section 4): a build-hash stamp of
// application behaviour, generated by tools/stamp-model-id.py and never hand-edited
// (the file's own GENERATED warning says so). Every S0 fixture records this id as
// provenance (tests/_fixture.js), so a stale golden is distinguishable from a real
// regression -- this file is what proves the id itself is trustworthy.
//
// Ordering matters here (see the idempotency test below): we independently
// RECOMPUTE the hash and check it against the stamped constant BEFORE ever
// invoking tools/stamp-model-id.py, because that script rewrites src/model-id.js
// -- a production file -- whenever the tree has drifted from the stamp. Only once
// we know the tree already matches the stamp do we run the script, and only to
// prove it is a no-op.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const zlib = require('node:zlib');
const { execFileSync } = require('node:child_process');
const { load } = require('../tools/logic-harness');

const ROOT = path.resolve(__dirname, '..');
const APP_FILE = path.join(ROOT, 'Experion Station Simulator.dc.html');
const MODEL_ID_FILE = path.join(ROOT, 'src', 'model-id.js');
const DIST_FILE = path.join(ROOT, 'dist', 'experion-station-sim-standalone.html');

const HEX64 = /^[0-9a-f]{64}$/;

test('src/model-id.js exports a 64-character lowercase hex string', () => {
  const id = require('../src/model-id.js');
  assert.equal(typeof id, 'string');
  assert.match(id, HEX64);
});

test('globalThis.ESS.MODEL_ID equals the module export, once the app modules load', () => {
  // require() takes the module.exports branch of model-id.js's UMD wrapper.
  // tools/logic-harness's load() evaluates the same source with `new Function`,
  // whose scope chain has no `module`, so the UMD wrapper's `else` branch runs
  // instead and assigns onto the passed-in root (globalThis) -- the browser path.
  const id = require('../src/model-id.js');
  load();
  assert.equal(typeof globalThis.ESS, 'object');
  assert.equal(globalThis.ESS.MODEL_ID, id);
});

test('src/model-id.js declares @artifact production and the generated-file warning in its first 3 lines', () => {
  const head = fs.readFileSync(MODEL_ID_FILE, 'utf8').split('\n').slice(0, 3).join('\n');
  assert.match(head, /@artifact\s+production\b/);
  assert.match(head, /GENERATED/);
  assert.match(head, /do not edit by hand/i);
});

// Independent recomputation of tools/stamp-model-id.py's hash (its inputs()/compute(),
// lines ~39-53): the app page, then every src/*.js EXCEPT model-id.js itself sorted by
// filename, each contributing its repo-relative POSIX path + NUL + its raw bytes + NUL,
// in that order.
function hashInputFiles() {
  const srcDir = path.join(ROOT, 'src');
  const mods = fs.readdirSync(srcDir)
    .filter(f => f.endsWith('.js') && f !== 'model-id.js')
    .sort()
    .map(f => path.join(srcDir, f));
  return [APP_FILE, ...mods];
}

function recomputeModelId() {
  const h = crypto.createHash('sha256');
  for (const abs of hashInputFiles()) {
    const rel = path.relative(ROOT, abs).split(path.sep).join('/');
    h.update(Buffer.from(rel, 'utf8'));
    h.update(Buffer.from([0]));
    h.update(fs.readFileSync(abs));
    h.update(Buffer.from([0]));
  }
  return h.digest('hex');
}

test('the stamped id equals an independent recomputation over the app page + src/*.js (excluding model-id.js)', () => {
  const stamped = require('../src/model-id.js');
  assert.equal(recomputeModelId(), stamped);
});

test('tools/stamp-model-id.py is idempotent: two runs leave the file byte-identical and report unchanged', (t) => {
  // This is only safe to exercise by actually invoking the script when the tree
  // already matches the stamp. Re-check that precondition here rather than trusting
  // the previous test's outcome or file order: node:test does not abort later tests
  // in a file when an earlier one fails, so without this guard, any src/*.js drift
  // (expected during S1-S5 active development) would make the assertions above
  // fail correctly in the previous test, then have THIS test silently execute
  // stamp-model-id.py anyway -- mutating src/model-id.js, a generated production
  // file, as a side effect of merely running `node --test`.
  const stamped = require('../src/model-id.js');
  if (recomputeModelId() !== stamped) {
    t.skip('tree does not match the stamped model id (see the recomputation test above); ' +
      'skipping rather than invoking stamp-model-id.py, which would mutate src/model-id.js');
    return;
  }
  const before = fs.readFileSync(MODEL_ID_FILE);
  const runOnce = () => execFileSync('python3', ['tools/stamp-model-id.py'], { cwd: ROOT, encoding: 'utf8' });

  const out1 = runOnce();
  const afterFirst = fs.readFileSync(MODEL_ID_FILE);
  const out2 = runOnce();
  const afterSecond = fs.readFileSync(MODEL_ID_FILE);

  assert.ok(before.equals(afterFirst), 'first run of stamp-model-id.py changed src/model-id.js bytes');
  assert.ok(afterFirst.equals(afterSecond), 'second run of stamp-model-id.py changed src/model-id.js bytes');
  assert.match(out1, /model-id unchanged:/);
  assert.match(out2, /model-id unchanged:/);
});

function localScriptSrcTags() {
  const html = fs.readFileSync(APP_FILE, 'utf8');
  return [...html.matchAll(/<script src="(\.\/[^"]+)"><\/script>/g)].map(m => m[1]);
}

function distManifest() {
  const html = fs.readFileSync(DIST_FILE, 'utf8');
  const m = html.match(/<script type="__bundler\/manifest">([\s\S]*?)<\/script>/);
  assert.ok(m, 'dist/experion-station-sim-standalone.html: no __bundler/manifest script tag found');
  return JSON.parse(m[1]);
}

test('model-id.js is a local script tag in the app page (so build-dist.py inlines it)', () => {
  const tags = localScriptSrcTags();
  assert.ok(tags.includes('./src/model-id.js'), `expected ./src/model-id.js among local script tags, got ${JSON.stringify(tags)}`);
});

test('dist manifest has at least one entry per local script tag in the app page (model-id.js included)', () => {
  // Measured today: 11 local <script src="./..."> tags (10 src/*.js modules incl.
  // model-id.js, plus support.js) and 13 manifest entries (those 11 plus 2 preserved
  // React ext_resources blobs) -- build-dist.py reads the existing dist to recover
  // those blobs, it does not synthesize this count, so ">=" is the honest assertion.
  const tagCount = localScriptSrcTags().length;
  const manifest = distManifest();
  assert.ok(tagCount >= 1, 'sanity: found no local <script src> tags in the app page to compare against');
  assert.ok(
    Object.keys(manifest).length >= tagCount,
    `dist manifest has ${Object.keys(manifest).length} entries, fewer than the ${tagCount} local script tags in the app page`
  );
});

test('exactly one dist manifest entry, decompressed, carries the stamped ESS.MODEL_ID', () => {
  const stamped = require('../src/model-id.js');
  const manifest = distManifest();
  const hits = [];
  for (const [key, entry] of Object.entries(manifest)) {
    const raw = Buffer.from(entry.data, 'base64');
    const content = entry.compressed ? zlib.gunzipSync(raw).toString('utf8') : raw.toString('utf8');
    if (content.includes(stamped)) hits.push(key);
  }
  assert.equal(hits.length, 1, `expected exactly 1 manifest entry to carry the stamped MODEL_ID, found ${hits.length} (${hits.join(', ')})`);
});
