#!/usr/bin/env python3
# @artifact dev
"""Reproduce the browser/CommonJS recipe directly from the committed JSON."""
from pathlib import Path
import json
root = Path(__file__).resolve().parents[2]
recipe = json.loads((root / 'tools/g2-live/recipe-v2.json').read_text())
output = '''// @artifact production
// Generated by tools/g2-live/generate-recipe.py; authority: tools/g2-live/recipe-v2.json.
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else(root.ESS=root.ESS||{}).MaterialRecipe=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const recipe = %s;
  function freeze(value){if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;}
  return freeze(recipe);
});
''' % json.dumps(recipe, indent=2, ensure_ascii=False)
(root / 'src/material-recipe.js').write_text(output)
