#!/usr/bin/env python3
# @artifact dev
"""Stamp src/model-id.js with the build hash of the simulator's behaviour.

`ESS.MODEL_ID` identifies the exact model build that produced a trajectory. A
seed alone is not enough once equations can change between releases: a fixture
digest captured under one set of process equations means nothing under another.
Every deterministic fixture records the MODEL_ID it was captured under, so a
stale golden is distinguishable from a real regression (V3-PLAN sections 4, 10).

The hash covers the application page and every `src/*.js` module EXCEPT
`src/model-id.js` itself, which is generated from that hash and so cannot be an
input to it. One pass converges; there is no fixpoint to iterate.

Run directly, or let `tools/build-dist.py` run it (it does, before bundling).
"""
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / 'Experion Station Simulator.dc.html'
OUT = ROOT / 'src' / 'model-id.js'

TEMPLATE = """// @artifact production
// GENERATED by tools/stamp-model-id.py -- do not edit by hand.
// sha256 of the application page plus every src/*.js module except this one.
// See docs/dev/V3-PLAN.md sections 4 and 10 (deterministic invariant).
(function (root, factory) {{
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else (root.ESS = root.ESS || {{}}).MODEL_ID = factory();
}})(typeof globalThis !== 'undefined' ? globalThis : this, function () {{
  'use strict';
  return '{model_id}';
}});
"""


def inputs():
    """The files whose bytes define simulator behaviour, in a stable order."""
    mods = sorted(p for p in (ROOT / 'src').glob('*.js') if p.name != 'model-id.js')
    return [APP] + mods


def compute():
    h = hashlib.sha256()
    for p in inputs():
        # Include the path so moving content between modules changes the hash.
        h.update(p.relative_to(ROOT).as_posix().encode('utf-8'))
        h.update(b'\0')
        h.update(p.read_bytes())
        h.update(b'\0')
    return h.hexdigest()


def main():
    model_id = compute()
    new = TEMPLATE.format(model_id=model_id)
    old = OUT.read_text(encoding='utf-8') if OUT.exists() else None
    if old == new:
        print(f'model-id unchanged: {model_id}')
        return 0
    OUT.write_text(new, encoding='utf-8')
    print(f'stamped src/model-id.js: {model_id} (over {len(inputs())} files)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
