// @artifact production
// GENERATED by tools/stamp-model-id.py -- do not edit by hand.
// sha256 of the application page plus every src/*.js module except this one.
// See docs/dev/V3-PLAN.md sections 4 and 10 (deterministic invariant).
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else (root.ESS = root.ESS || {}).MODEL_ID = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  return '5f6adbed74af2c8ed98acf77f61a29660ad4fa6cc909fea5a1eff84c35e62d66';
});
