// @artifact production
// GENERATED by tools/stamp-model-id.py -- do not edit by hand.
// sha256 of the application page plus every src/*.js module except this one.
// See docs/dev/V3-PLAN.md sections 4 and 10 (deterministic invariant).
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else (root.ESS = root.ESS || {}).MODEL_ID = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  return '599e173b2358c5e8ebe5ff43745fc4d591caf0fa9c2a8b3d3f45e3e540130610';
});
